
service: sls-blog

plugins:
  - serverless-offline
custom:
  stackName: ${opt:stackName, 'qa'}
#app and org for use with dashboard.serverless.com
app: sls-blog
org: trido

provider:
  name: aws
  runtime: nodejs12.x
  stage: qa
  region: ap-southeast-1
  timeout: 10

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: api/hello
          method: GET