
service: sls-blog

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: qa
  region: ap-southeast-1
  timeout: 10

functions:
  helloWorld:
    handler: handler.helloWorld
    events:
      - http:
          path: api/hello
          method: GET